### ISSUE TITLE
A route for the e-mail verification link

### ISSUE THREAD

**Issue by MasterSlicer** [fossasia/accounts.susi.ai#136]
**Actual Behaviour**

Clicking the e-mail verification link redirects to a link which has the JSON data

**Expected Behaviour**

A route is to be generated for the account verification link which redirects to the accounts.

**Would you like to work on the issue?**
Yes

**Comment by DravitLochan** [comment]
@MasterSlicer Are you well aware with ReactJS? What needs to be done here is user would be redirected to accounts when clicked on the link with 'accountVerificationToken' as a parameter. Final link would look like http://accounts.susi.ai/accountVerificationToken={30 characters long token}. Should I assign this to you so that you can start with it?

**Comment by MasterSlicer** [comment]
I am not well acquainted with ReactJS..but i can get well versed very soon.

**Comment by DravitLochan** [comment]
Well then I'll fix this issue and notify you so that you can send your first patch to fix just the link on the server.Does that works?

**Comment by MasterSlicer** [comment]
Yup that'll work.
