### ISSUE TITLE
Add Google Sign In feature for SUSI.AI

### ISSUE THREAD

**Issue by PrP-11** [fossasia/accounts.susi.ai#242]
**Actual Behaviour**
Currently we need to make a new account on SUSI and we don't have another options to sign in like Google Sign in Using OAuth 2.0

**Expected Behaviour**
Google is providing OAuth Service. We can implement Google Login so that user doesn't need to remember another password for SUSI. We can also store data from their google accounts to implement new skills

**Would you like to work on the issue?**
Yes, but I need some help on server and database side.

**Comment by prateekiiest** [comment]
Am interested in working on this too.
See my proposed plan in the above referenced issue

**Comment by imjog** [comment]
Hi @PrP-11 @prateekiiest Can you please make it the priority. and are you planning to add auth for Tweeter and Facebook too? I am waiting for server-side implementation to implement it on iOS. I think @Orbiter can help you regarding server and database side.

**Comment by prateekiiest** [comment]
First we can work with the Google sign in api, then we can move forward to the others.

**Comment by mariobehling** [comment]
When people login with Google, they always need to create an account with SUSI.AI. Otherwise this feature does not make sense. Compare how other services do this, e.g. Pinterest.

In regards to feature completeness this issue has low priority. We already discussed in meetings our priorities. Would be great if you actually focus on them, e.g. Wifi-Direct.
