### ISSUE TITLE
Migrate accounts.susi.ai from Angular to React

### ISSUE THREAD

**Issue by jyoth1raditya** [fossasia/accounts.susi.ai#42]
Anugular 1 support is slowly decreasing and will be depreciated. 
We need to migrate `accounts.susi.ai` to Angular2.

**Comment by DravitLochan** [comment]
@mariobehling  The website http://accounts.susi.ai is live and I think things are pretty stable. To migrate to Angular2, I propose that we start from scratch and not refactor existing code. We will indeed recycle the previous code smartly. Why? Because the code is little less documented. And I personally believe that in a codebase big enough, It will take more time to edit then to start from 0 and implement things.

**Comment by jyoth1raditya** [comment]
@mariobehling , I agree with dravit. We will reuse the code as much as possible. Angular 1 and 2 are very different in structure and implementation. So, We can do better by working from scratch and reusing the code whenever required.

**Comment by mariobehling** [comment]
@jyoth1raditya @DravitLochan Good points. It is good to see, that you understand the apps now.

As Angular 2 is a complete rewrite, we should consider if it makes sense. In order to align, I tend to follow the web chat in that case and use React for the next steps. This would make components reusable.
